In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Primera Division Argentina - passing.csv')

In [7]:
df.sample(5)

,Unnamed: 0,Player,passing_Nation,passing_Pos,passing_Squad,passing_Comp,passing_Age,passing_Born,passing_90s,passing_Cmp,...,passing_Cmp%.3,passing_Ast,passing_xAG,passing_xA,passing_A-xAG,passing_KP,passing_1/3,passing_PPA,passing_CrsPA,passing_PrgP
440,440,Lucas Janson,ar ARG,"MF,FW",Boca Juniors,Primera Division Argentina,30-050,1994,1.1,19,...,100.0,0,0.1,0.0,-0.1,2,3,0,0,3
901,901,Lionel Verde,0,"MF,DF",Unión,Primera Division Argentina,0,0,0.4,10,...,50.0,0,0.1,0.1,-0.1,1,3,1,0,3
769,769,Braian Romero,ar ARG,FW,Vélez Sarsfield,Primera Division Argentina,33-112,1991,14.2,168,...,50.0,2,2.3,2.3,-0.3,7,8,3,0,15
780,780,Marco Ruben,ar ARG,FW,Rosario Central,Primera Division Argentina,37-345,1986,3.3,31,...,100.0,0,0.2,0.1,-0.2,2,8,1,1,12
584,584,Pablo Monje,ar ARG,MF,Deportivo Riestra,Primera Division Argentina,27-242,1997,14.2,249,...,42.7,0,0.6,0.8,-0.6,11,44,2,1,42

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 928 entries, 0 to 927
Data columns (total 32 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       928 non-null    int64
 1   Player           928 non-null    object
 2   passing_Nation   928 non-null    object
 3   passing_Pos      928 non-null    object
 4   passing_Squad    928 non-null    object
 5   passing_Comp     928 non-null    object
 6   passing_Age      928 non-null    object
 7   passing_Born     928 non-null    int64
 8   passing_90s      928 non-null    float64
 9   passing_Cmp      928 non-null    int64
 10  passing_Att      928 non-null    int64
 11  passing_Cmp%     928 non-null    float64
 12  passing_TotDist  928 non-null    int64
 13  passing_PrgDist  928 non-null    int64
 14  passing_Cmp.1    928 non-null    int64
 15  passing_Att.1    928 non-null    int64
 16  passing_Cmp%.1   928 non-null    float64
 17  passing_Cmp.2    928 non-null    int64
 18  passing_Att.2    928 non-null    int64
 19  passing_Cmp%.2   928 non-null    float64
 20  passing_Cmp.3    928 non-null    int64
 21  passing_Att.3    928 non-null    int64
 22  passing_Cmp%.3   928 non-null    float64
 23  passing_Ast      928 non-null    int64
 24  passing_xAG      928 non-null    float64
 25  passing_xA       928 non-null    float64
 26  passing_A-xAG    928 non-null    float64
 27  passing_KP       928 non-null    int64
 28  passing_1/3      928 non-null    int64
 29  passing_PPA      928 non-null    int64
 30  passing_CrsPA    928 non-null    int64
 31  passing_PrgP     928 non-null    int64
dtypes: float64(8), int64(18), object(6)
memory usage: 232.1+ KB

In [10]:
list(df.columns)

['Unnamed: 0',
 'Player',
 'passing_Nation',
 'passing_Pos',
 'passing_Squad',
 'passing_Comp',
 'passing_Age',
 'passing_Born',
 'passing_90s',
 'passing_Cmp',
 'passing_Att',
 'passing_Cmp%',
 'passing_TotDist',
 'passing_PrgDist',
 'passing_Cmp.1',
 'passing_Att.1',
 'passing_Cmp%.1',
 'passing_Cmp.2',
 'passing_Att.2',
 'passing_Cmp%.2',
 'passing_Cmp.3',
 'passing_Att.3',
 'passing_Cmp%.3',
 'passing_Ast',
 'passing_xAG',
 'passing_xA',
 'passing_A-xAG',
 'passing_KP',
 'passing_1/3',
 'passing_PPA',
 'passing_CrsPA',
 'passing_PrgP']

In [14]:
df.shape[0]

928

In [17]:
df.describe()

,Unnamed: 0,passing_Born,passing_90s,passing_Cmp,passing_Att,passing_Cmp%,passing_TotDist,passing_PrgDist,passing_Cmp.1,passing_Att.1,...,passing_Cmp%.3,passing_Ast,passing_xAG,passing_xA,passing_A-xAG,passing_KP,passing_1/3,passing_PPA,passing_CrsPA,passing_PrgP
count,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,...,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000
mean,463.500000,1974.190733,5.266595,146.744612,202.418103,69.444181,2779.434267,1150.975216,60.299569,72.908405,...,45.990733,0.314655,0.353879,0.355388,-0.039224,4.073276,13.391164,3.157328,1.148707,17.051724
std,268.034824,216.396464,4.548376,150.143608,195.637469,13.604375,3039.743129,1501.241174,61.198959,71.880093,...,24.405677,0.738903,0.554131,0.527632,0.486531,5.400170,16.512720,4.530019,2.251567,20.440075
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,-2.200000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,231.750000,1994.000000,1.300000,30.000000,44.000000,63.600000,471.000000,142.750000,12.000000,15.000000,...,35.300000,0.000000,0.000000,0.000000,-0.200000,0.000000,2.000000,0.000000,0.000000,2.000000
50%,463.500000,1999.000000,4.050000,93.000000,138.500000,70.600000,1596.000000,544.000000,40.000000,50.000000,...,49.050000,0.000000,0.100000,0.100000,0.000000,2.000000,7.000000,1.000000,0.000000,10.000000
75%,695.250000,2002.000000,8.425000,228.250000,319.750000,78.100000,4245.000000,1614.000000,93.000000,115.000000,...,60.000000,0.000000,0.500000,0.500000,0.000000,6.000000,19.000000,4.000000,1.000000,25.000000
max,927.000000,2008.000000,16.000000,906.000000,1049.000000,100.000000,19562.000000,10925.000000,313.000000,348.000000,...,100.000000,5.000000,4.400000,3.800000,2.700000,37.000000,121.000000,35.000000,19.000000,149.000000