In [21]:
import pandas as pd
import numpy as np
import LanusStats as ls

In [2]:
fotmob = ls.FotMob()

In [3]:
tabla_xG = fotmob.get_season_tables('Argentina Primera Division', '2024', 'xg')

In [8]:
tabla_xG = tabla_xG[['name', 'shortName', 'pageUrl', 'xg',
       'xgConceded', 'xPoints']]

In [14]:
tabla_promiedos = pd.read_html('https://www.promiedos.com.ar/primera', encoding='latin1')[0]

In [20]:
tabla_promiedos.head()

   #       Equipo  Pts  PJ  PG  PE  PP  GF  GC  DIF
0  1        Velez   42  21  12   6   3  34  14   20
1  2      Huracan   42  22  11   9   2  25  11   14
2  3        Union   36  22  10   6   6  24  21    3
3  4  Racing Club   34  21  10   4   7  30  20   10
4  5  River Plate   33  21   8   9   4  27  16   11

In [28]:
tabla_xG['Equipo'] = tabla_xG['name']

In [30]:
tabla_xG.head()

,name,shortName,pageUrl,xg,xgConceded,xPoints,Equipo
0,River Plate,River Plate,/teams/10076/overview/river-plate,32.1183,18.6529,37.460020,River Plate
1,Atletico Tucuman,Atletico Tucuman,/teams/161727/overview/atletico-tucuman,30.5408,23.6538,35.565036,Atletico Tucuman
2,Velez Sarsfield,Velez Sarsfield,/teams/10079/overview/velez-sarsfield,30.0607,19.9022,35.054402,Velez Sarsfield
3,Racing Club,Racing Club,/teams/10080/overview/racing-club,28.0060,19.5845,34.811524,Racing Club
4,Estudiantes,Estudiantes,/teams/10094/overview/estudiantes,25.5555,21.4939,33.298517,Estudiantes

In [32]:
tabla_promiedos.merge(tabla_xG, how = 'inner', left_on='Equipo', right_on = 'name', suffixes=['_tabla1', '_tabla2'])

,#,Equipo_tabla1,Pts,PJ,PG,PE,PP,GF,GC,DIF,name,shortName,pageUrl,xg,xgConceded,xPoints,Equipo_tabla2
0,2,Huracan,42,22,11,9,2,25,11,14,Huracan,Huracan,/teams/10081/overview/huracan,22.4416,19.0335,32.234360,Huracan
1,3,Union,36,22,10,6,6,24,21,3,Union,Union,/teams/10096/overview/union,24.8710,21.2036,33.286942,Union
2,4,Racing Club,34,21,10,4,7,30,20,10,Racing Club,Racing Club,/teams/10080/overview/racing-club,28.0060,19.5845,34.811524,Racing Club
3,5,River Plate,33,21,8,9,4,27,16,11,River Plate,River Plate,/teams/10076/overview/river-plate,32.1183,18.6529,37.460020,River Plate
4,9,Independiente,30,22,6,12,4,19,14,5,Independiente,Independiente,/teams/10078/overview/independiente,16.5427,18.2110,27.272535,Independiente
5,11,Instituto,29,21,8,5,8,27,22,5,Instituto,Instituto,/teams/10090/overview/instituto,21.9755,21.8008,28.512017,Instituto
6,14,Boca Juniors,28,21,7,7,7,25,23,2,Boca Juniors,Boca Juniors,/teams/10077/overview/boca-juniors,26.5403,29.0628,25.799526,Boca Juniors
7,15,Godoy Cruz,28,21,6,10,5,23,23,0,Godoy Cruz,Godoy Cruz,/teams/10227/overview/godoy-cruz,24.1951,25.5883,27.733158,Godoy Cruz
8,16,San Lorenzo,28,22,7,7,8,18,19,-1,San Lorenzo,San Lorenzo,/teams/10083/overview/san-lorenzo,19.4434,21.3149,28.561901,San Lorenzo
9,17,Belgrano,27,21,6,9,6,24,24,0,Belgrano,Belgrano,/teams/10092/overview/belgrano,21.7038,23.8920,26.242853,Belgrano
10,18,Tigre,26,21,6,8,7,25,24,1,Tigre,Tigre,/teams/89396/overview/tigre,21.3817,24.7420,26.689173,Tigre
11,19,Lanus,26,21,6,8,7,22,28,-6,Lanus,Lanus,/teams/10082/overview/lanus,22.2430,26.8257,27.216628,Lanus
12,20,Rosario Central,25,22,6,7,9,23,22,1,Rosario Central,Rosario Central,/teams/10084/overview/rosario-central,22.0079,18.8424,32.482038,Rosario Central
13,24,Banfield,22,21,5,7,9,20,27,-7,Banfield,Banfield,/teams/10087/overview/banfield,23.2733,28.4792,24.094800,Banfield
14,28,Barracas Central,16,21,3,7,11,10,26,-16,Barracas Central,Barracas Central,/teams/213534/overview/barracas-central,14.8693,29.4565,18.237703,Barracas Central